export class ProductsItem {
  url = "../../assets/products/";

  productsData = [
    {
      id: 1,
      title: "Trendy T-Shirt",
      price: 19.99,
      imgUrl: this.url + "1.jpg",
      hoverUrl: this.url + "26.jpg",
    },
    {
      id: 2,
      title: "Slim Fit Jeans",
      price: 39.99,
      imgUrl: this.url + "2.jpg",
      hoverUrl: this.url + "27.jpg",
    },
    {
      id: 3,
      title: "Classic Fedora Hat",
      price: 24.99,
      imgUrl: this.url + "3.jpg",
      hoverUrl: this.url + "28.jpg",
    },
    {
      id: 4,
      title: "Running Shoes",
      price: 49.99,
      imgUrl: this.url + "4.jpg",
      hoverUrl: this.url + "29.jpg",
    },
    {
      id: 5,
      title: "Casual Button-Down Shirt",
      price: 29.99,
      imgUrl: this.url + "5.jpg",
      hoverUrl: this.url + "30.jpg",
    },
    {
      id: 6,
      title: "Cargo Shorts",
      price: 34.99,
      imgUrl: this.url + "6.jpg",
      hoverUrl: this.url + "31.jpg",
    },
    {
      id: 7,
      title: "Beanie with Pom-Pom",
      price: 14.99,
      imgUrl: this.url + "7.jpg",
      hoverUrl: this.url + "32.jpg",
    },
    {
      id: 8,
      title: "Sneakers with Velcro",
      price: 54.99,
      imgUrl: this.url + "8.jpg",
      hoverUrl: this.url + "33.jpg",
    },
    {
      id: 9,
      title: "Hooded Sweatshirt",
      price: 44.99,
      imgUrl: this.url + "9.jpg",
      hoverUrl: this.url + "34.jpg",
    },
    {
      id: 10,
      title: "Khaki Chinos",
      price: 37.99,
      imgUrl: this.url + "10.jpg",
      hoverUrl: this.url + "35.jpg",
    },
    {
      id: 11,
      title: "Straw Sun Hat",
      price: 19.99,
      imgUrl: this.url + "11.jpg",
      hoverUrl: this.url + "36.jpg",
    },
    {
      id: 12,
      title: "Leather Loafers",
      price: 59.99,
      imgUrl: this.url + "12.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 13,
      title: "Striped Polo Shirt",
      price: 27.99,
      imgUrl: this.url + "13.jpg",
      hoverUrl: this.url + "2.jpg",
    },
    {
      id: 14,
      title: "Denim Jacket",
      price: 49.99,
      imgUrl: this.url + "14.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 15,
      title: "Athletic Socks (Pack of 3)",
      price: 9.99,
      imgUrl: this.url + "15.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 16,
      title: "Cargo Pants",
      price: 34.99,
      imgUrl: this.url + "16.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 17,
      title: "Fedora with Feather",
      price: 29.99,
      imgUrl: this.url + "17.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 18,
      title: "Canvas Slip-On Shoes",
      price: 39.99,
      imgUrl: this.url + "18.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 19,
      title: "Plaid Flannel Shirt",
      price: 32.99,
      imgUrl: this.url + "19.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 20,
      title: "Jogger Sweatpants",
      price: 29.99,
      imgUrl: this.url + "20.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 21,
      title: "Bowler Hat",
      price: 19.99,
      imgUrl: this.url + "21.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 22,
      title: "Leather Ankle Boots",
      price: 64.99,
      imgUrl: this.url + "22.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 23,
      title: "Rugby Polo Shirt",
      price: 27.99,
      imgUrl: this.url + "23.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 24,
      title: "Corduroy Blazer",
      price: 59.99,
      imgUrl: this.url + "24.jpg",
      hoverUrl: this.url + "1.jpg",
    },
    {
      id: 25,
      title: "High-Top Sneakers",
      price: 49.99,
      imgUrl: this.url + "25.jpg",
      hoverUrl: this.url + "1.jpg",
    },
  ];
}
